// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MemoDbContext))]
    partial class MemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WeddingId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("backend.Models.Planner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Planners");
                });

            modelBuilder.Entity("backend.Models.WQRCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssetUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Scans")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("WeddingId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WeddingId")
                        .IsUnique();

                    b.ToTable("QRCodes");
                });

            modelBuilder.Entity("backend.Models.WeddingStory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CoupleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HowWeMet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PlannerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Proposal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThankYouMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PlannerId");

                    b.ToTable("Weddings");
                });

            modelBuilder.Entity("backend.Models.Media", b =>
                {
                    b.HasOne("backend.Models.WeddingStory", "Wedding")
                        .WithMany("Gallery")
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wedding");
                });

            modelBuilder.Entity("backend.Models.WQRCode", b =>
                {
                    b.HasOne("backend.Models.WeddingStory", "Wedding")
                        .WithOne("QRCode")
                        .HasForeignKey("backend.Models.WQRCode", "WeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wedding");
                });

            modelBuilder.Entity("backend.Models.WeddingStory", b =>
                {
                    b.HasOne("backend.Models.Planner", null)
                        .WithMany("Weddings")
                        .HasForeignKey("PlannerId");
                });

            modelBuilder.Entity("backend.Models.Planner", b =>
                {
                    b.Navigation("Weddings");
                });

            modelBuilder.Entity("backend.Models.WeddingStory", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("QRCode")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
